/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simplificacaodecircuitos;

import java.awt.Color;
import java.util.Arrays;

/**
 *
 * @author mfernandes
 */
public class Mostrar extends javax.swing.JFrame {

    String[] ensa;

    /**
     * Creates new form Mostrar
     */
    public Mostrar(String[] ensa, String[] normal) {
        initComponents();
        this.ensa = ensa;
        System.out.println(Arrays.toString(ensa));
        int i = 0;
        for (String string : ensa) {

            String str = string.replace("simp ", "");

            jTextArea1.append(normal[i++] + "\n" + str + "\n");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        f = new javax.swing.JLabel();
        b = new javax.swing.JLabel();
        e = new javax.swing.JLabel();
        c = new javax.swing.JLabel();
        a = new javax.swing.JLabel();
        g = new javax.swing.JLabel();
        d = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        f.setBackground(new java.awt.Color(0, 0, 0));
        f.setOpaque(true);

        b.setBackground(new java.awt.Color(0, 0, 0));
        b.setOpaque(true);

        e.setBackground(new java.awt.Color(0, 0, 0));
        e.setOpaque(true);

        c.setBackground(new java.awt.Color(0, 0, 0));
        c.setOpaque(true);

        a.setBackground(new java.awt.Color(0, 0, 0));
        a.setOpaque(true);

        g.setBackground(new java.awt.Color(0, 0, 0));
        g.setOpaque(true);

        d.setBackground(new java.awt.Color(0, 0, 0));
        d.setOpaque(true);

        jToggleButton1.setText("A");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("B");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        jToggleButton3.setText("C");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        jToggleButton4.setText("D");
        jToggleButton4.setToolTipText("");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel1.setText("...");

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 48)); // NOI18N
        jLabel2.setText("0");

        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(g, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(e, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)
                                .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)
                                .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(a, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(161, 161, 161))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(g, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(e, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)))
                .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        // TODO add your handling code here:
        display();
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    void display() {
        a.setBackground(Color.getColor("[214,217,223]"));
        b.setBackground(Color.getColor("[214,217,223]"));
        c.setBackground(Color.getColor("[214,217,223]"));
        d.setBackground(Color.getColor("[214,217,223]"));
        e.setBackground(Color.getColor("[214,217,223]"));
        f.setBackground(Color.getColor("[214,217,223]"));
        g.setBackground(Color.getColor("[214,217,223]"));
        //simp g = abC + aBc + Abc + aBCd 
        for (String string : ensa) {

            String str = string.replace("simp ", "");

            String saida = str.split(" = ")[0];
            String exs = str.split(" = ")[1];

            boolean ligar = false;

            // System.out.println(exs);
            for (String expresao : exs.replace(" ", "").split("\\+")) {
                // System.out.println(">"+expresao);
                if (((!expresao.contains("A") && !expresao.contains("a")) || (expresao.contains("A") && jToggleButton1.isSelected()) || (expresao.contains("a") && !jToggleButton1.isSelected()))
                        && ((!expresao.contains("B") && !expresao.contains("b")) || (expresao.contains("B") && jToggleButton2.isSelected()) || (expresao.contains("b") && !jToggleButton2.isSelected()))
                        && ((!expresao.contains("C") && !expresao.contains("c")) || (expresao.contains("C") && jToggleButton3.isSelected()) || (expresao.contains("c") && !jToggleButton3.isSelected()))
                        && ((!expresao.contains("D") && !expresao.contains("d")) || (expresao.contains("D") && jToggleButton4.isSelected()) || (expresao.contains("d") && !jToggleButton4.isSelected()))) {
                    ligar = true;
                    //System.out.println("certo " + saida + " para " + expresao);
                    break;
                }
            }

            if (ligar) {
                char ch = saida.charAt(0);

                switch (ch) {
                    case 'a':
                        a.setBackground(Color.red);
                        break;
                    case 'b':
                        b.setBackground(Color.red);
                        break;
                    case 'c':
                        c.setBackground(Color.red);
                        break;
                    case 'd':
                        d.setBackground(Color.red);
                        break;
                    case 'e':
                        e.setBackground(Color.red);
                        break;
                    case 'f':
                        f.setBackground(Color.red);
                        break;
                    case 'g':
                        g.setBackground(Color.red);
                        break;
                }

            }
        }

        //System.out.println("\n --------------------");
        String a = "0", b = "0", c = "0", d = "0";
        int i = 0;
        if (jToggleButton1.isSelected()) {
            a = "1";
            i += 8;
        }
        if (jToggleButton2.isSelected()) {
            b = "1";
            i += 4;
        }
        if (jToggleButton3.isSelected()) {
            c = "1";
            i += 2;
        }
        if (jToggleButton4.isSelected()) {
            d = "1";
            i += 1;
        }

        jLabel1.setText(a + b + c + d);

        jLabel2.setText(String.valueOf(i));
    }


    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        // TODO add your handling code here:

        int i = (int) jSpinner1.getValue();

        if (i >= 8) {
            i -= 8;
            jToggleButton1.setSelected(true);

        } else {
            jToggleButton1.setSelected(false);
        }
        if (i >= 4) {
            i -= 4;
            jToggleButton2.setSelected(true);

        } else {
            jToggleButton2.setSelected(false);
        }
        if (i >= 2) {
            i -= 2;
            jToggleButton3.setSelected(true);

        } else {
            jToggleButton3.setSelected(false);
        }
        if (i >= 1) {
            i -= 1;
            jToggleButton4.setSelected(true);

        } else {
            jToggleButton4.setSelected(false);
        }
        display();
    }//GEN-LAST:event_jSpinner1StateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private javax.swing.JLabel b;
    private javax.swing.JLabel c;
    private javax.swing.JLabel d;
    private javax.swing.JLabel e;
    private javax.swing.JLabel f;
    private javax.swing.JLabel g;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    // End of variables declaration//GEN-END:variables
}
